# This query is run against the Turtle files in https://github.com/egonw/jcheminform-kb
#
PREFIX jcheminf: <https://jcheminf.biomedcentral.com/ontology/>
PREFIX doi:      <http://www.wikidata.org/prop/direct/P356>

SELECT ?doi WHERE {
  ?article doi: ?doi .
}
