PREFIX jcheminf: <https://jcheminf.biomedcentral.com/ontology/>
PREFIX doi:      <http://www.wikidata.org/prop/direct/P356>

SELECT ?doi WHERE {
  ?article jcheminf:hasCiTOAnnotation "true" ;
           doi: ?doi .
}
